In [9]:
import pandas as pd
from pycaret.regression import *

In [20]:
# Memuat data dari lokasi file
data = pd.read_csv('C:/Users/USER/Semester 4_MLOps/fitness/fitness.csv')

# Menghapus kolom 'UserID' dan 'Date'
data = data.drop(['UserID', 'Date'], axis=1)

data

,Total_Distance,Tracker_Distance,Logged_Activities_Distance,Very_Active_Distance,Moderately_Active_Distance,Light_Active_Distance,Sedentary_Active_Distance,Very_Active_Minutes,Fairly_Active_Minutes,Lightly_Active_Minutes,Sedentary_Minutes,Steps,Calories_Burned
0,8.02,8.02,0.0,2.03,0.48,5.52,0.0,26,10,349,587,10449,2536
1,5.82,5.82,0.0,2.28,0.90,2.64,0.0,30,16,135,1259,8001,2902
2,0.11,0.11,0.0,0.00,0.00,0.11,0.0,0,0,12,1303,152,2100
3,7.21,7.21,0.0,0.00,0.34,6.87,0.0,0,7,352,1077,9543,2450
4,7.86,7.86,0.0,0.34,0.73,6.79,0.0,6,19,258,1020,10218,3013
...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0,0,0,1440,0,1347
936,1.70,1.70,0.0,0.00,0.35,1.34,0.0,0,8,160,1272,2524,1529
937,7.35,7.35,0.0,0.53,2.03,4.75,0.0,7,44,238,1151,9423,3012
938,7.38,7.38,0.0,0.63,1.67,5.09,0.0,12,39,199,896,9603,2899
939,3.55,3.55,0.0,0.00,0.00,3.55,0.0,0,0,220,1220,5372,1827

In [21]:
# Setup regression
s = setup(data, target='Calories_Burned', session_id=123)

# Membuat model regresi
best = compare_models()

# Melakukan tuning pada model terbaik
model = tune_model(best)

# Menampilkan evaluasi model
evaluate_model(model)

# Menyelesaikan model
finalize_model(model)

# Menyimpan model ke file .pkl
save_model(model, 'calories_regression_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['Total_Distance',
                                              'Tracker_Distance',
                                              'Logged_Activities_Distance',
                                              'Very_Active_Distance',
                                              'Moderately_Active_Distance',
                                              'Light_Active_Distance',
                                              'Sedentary_Active_Distance',
                                              'Very_Active_Minutes',
                                              'Fairly_Active_Minutes',
                                              'Lightly_Active_Minutes',
                                              'Sedentary_Minutes', 'Steps'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', BayesianRidge())]),
 'calories_regression_model.pkl')