In [6]:
import pandas as pd
from pycaret.datasets import get_data
from pycaret.classification import *

In [7]:
# Memuat data dari lokasi file
data = pd.read_csv('C:/Users/USER/Semester 4_MLOps/heart_failure/heart_failure_clinical_records_dataset.csv')
data

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [8]:
# Setup klasifikasi
s = setup(data, target='DEATH_EVENT', session_id=123)

# Membuat model klasifikasi
best = compare_models()

# Melakukan tuning pada model terbaik
tuned_model = tune_model(best)

# Menampilkan evaluasi model
evaluate_model(tuned_model)

# Menyelesaikan model
final_model = finalize_model(tuned_model)

# Menyimpan model ke file .pkl
save_model(final_model, 'heart_failure_classification_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'anaemia',
                                              'creatinine_phosphokinase',
                                              'diabetes', 'ejection_fraction',
                                              'high_blood_pressure', 'platelets',
                                              'serum_creatinine', 'serum_sodium',
                                              'sex', 'smoking', 'time'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, n_estimators=100,
                                         n_jobs=-1, oob_score=False,
                                         random_state=123, verbose=0,
                                         warm_start=False))],
          verbose=False),
 'heart_failure_classification_model.pkl')