In [2]:
import pandas as pd
from pycaret.classification import *

# Memuat data dari lokasi file
data = pd.read_csv('C:/Users/USER/Semester 4_MLOps/migraine/migraine_data.csv')

# Menghapus kolom 'UserID' dan 'Date'
data = data.drop(['DPF'], axis=1)

data

,Age,Duration,Frequency,Location,Character,Intensity,Nausea,Vomit,Phonophobia,Photophobia,...,Dysarthria,Vertigo,Tinnitus,Hypoacusis,Diplopia,Defect,Ataxia,Conscience,Paresthesia,Type
0,30,1,5,1,1,2,1,0,1,1,...,0,0,0,0,0,0,0,0,0,Typical aura with migraine
1,50,3,5,1,1,3,1,1,1,1,...,0,1,0,0,0,0,0,0,0,Typical aura with migraine
2,53,2,1,1,1,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,Typical aura with migraine
3,45,3,5,1,1,3,1,0,1,1,...,0,1,0,0,0,0,0,0,0,Typical aura with migraine
4,53,1,1,1,1,2,1,0,1,1,...,0,0,0,0,0,0,0,0,0,Typical aura with migraine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,39,1,1,1,1,3,1,1,1,1,...,0,1,0,0,1,0,0,0,0,Basilar-type aura
396,20,3,2,1,1,3,1,0,1,1,...,0,0,1,1,0,0,0,0,0,Basilar-type aura
397,28,3,2,1,1,3,1,0,1,1,...,0,1,0,0,0,1,0,0,0,Basilar-type aura
398,20,3,1,1,1,3,1,0,1,1,...,0,1,0,0,0,0,0,0,1,Basilar-type aura
399,37,1,1,1,1,3,1,1,1,1,...,0,1,0,0,0,0,0,1,0,Basilar-type aura

In [3]:
# Setup klasifikasi
s = setup(data, target='Type', session_id=123)

# Membuat model klasifikasi
best = compare_models()

# Melakukan tuning pada model terbaik
model = tune_model(best)

# Menampilkan evaluasi model
evaluate_model(model)

# Menyelesaikan model
finalize_model(model)

# Menyimpan model ke file .pkl
save_model(model, 'migraine_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Age', 'Duration', 'Frequency',
                                              'Location', 'Character',
                                              'Intensity', 'Nausea', 'Vomit',
                                              'Phonophobia', 'Photophobia',
                                              'Visual', 'Sensory', 'Dysphasia',...
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None, include=[],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  GaussianNB(priors=None, var_smoothing=2e-07))],
          verbose=False),
 'migraine_model.pkl')